// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLrz5QRXftxYK9Q1YeWoAAMkdXuo3gNQI',
    appId: '1:1074894786105:web:f1dff8f5afd1cf16a447e8',
    messagingSenderId: '1074894786105',
    projectId: 'fir-flutter-codelab-69996',
    authDomain: 'fir-flutter-codelab-69996.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-69996.appspot.com',
    measurementId: 'G-G0FNDVZG8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIasSrzG85FB-eviDbvtA1Z_LMokI-EJs',
    appId: '1:1074894786105:android:b42893c74a9e4342a447e8',
    messagingSenderId: '1074894786105',
    projectId: 'fir-flutter-codelab-69996',
    storageBucket: 'fir-flutter-codelab-69996.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIpLD0DA5yljdT0ioqaF94m8AHHLAgn3s',
    appId: '1:1074894786105:ios:e76746f7e4ac00c4a447e8',
    messagingSenderId: '1074894786105',
    projectId: 'fir-flutter-codelab-69996',
    storageBucket: 'fir-flutter-codelab-69996.appspot.com',
    iosClientId: '1074894786105-tss9j3qigs3amblgnv7du0sfrngb45al.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIpLD0DA5yljdT0ioqaF94m8AHHLAgn3s',
    appId: '1:1074894786105:ios:e76746f7e4ac00c4a447e8',
    messagingSenderId: '1074894786105',
    projectId: 'fir-flutter-codelab-69996',
    storageBucket: 'fir-flutter-codelab-69996.appspot.com',
    iosClientId: '1074894786105-tss9j3qigs3amblgnv7du0sfrngb45al.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
